name: Running tests

on: [push]

jobs:

  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pytest:latest
    - name: Start tests
      run: docker run -v `pwd`:/tmp/ pytest /usr/local/bin/pytest -s /tmp/api_server
